# Generated by Django 3.0.5 on 2020-06-15 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_product_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('number', models.CharField(default=0, max_length=12)),
                ('units', models.IntegerField(default=1)),
                ('total', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('NEW', 'Nueva'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='NEW', max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=50, help_text='Este valor hace referencia en porciente'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0, help_text='Este es el precio original sin descuento'),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField(default=1)),
                ('total', models.FloatField(default=0.0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='business.Product')),
            ],
        ),
    ]
