# Generated by Django 3.0.5 on 2020-06-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20200621_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='units',
            field=models.IntegerField(default=1),
        ),
    ]
